# Generated by Django 4.0.4 on 2023-02-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatId', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='座位ID')),
                ('seatType', models.SmallIntegerField(choices=[(1, '自习区'), (2, '阅读区'), (3, '休闲区')], default=1, verbose_name='座位类型')),
                ('seatFloor', models.SmallIntegerField(choices=[(1, '一楼'), (2, '二楼'), (3, '三楼'), (4, '四楼'), (5, '五楼')], default=1, verbose_name='所在楼层')),
                ('seatStatus', models.SmallIntegerField(choices=[(1, '未预约'), (2, '已预约'), (3, '已就坐')], default=1, verbose_name='座位状态')),
                ('seatPower', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=2, verbose_name='拥有电源')),
                ('seatCorridor', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=2, verbose_name='靠近走廊')),
                ('seatOrder', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=2, verbose_name='需要预约')),
            ],
        ),
    ]
