# Generated by Django 4.0.4 on 2023-02-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='用户密码')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='公告编号')),
                ('title', models.CharField(max_length=255, verbose_name='公告标题')),
                ('context', models.TextField(verbose_name='公告内容')),
                ('file', models.FileField(blank=True, upload_to='files/', verbose_name='公告附件')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('createName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.adminuser')),
            ],
        ),
    ]
