# Generated by Django 4.1.2 on 2023-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='用户密码')),
            ],
        ),
        migrations.CreateModel(
            name='BlackUser',
            fields=[
                ('userId', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('cancelTime', models.DateTimeField(verbose_name='解除时间')),
                ('blackCause', models.TextField(default='系统拉黑', verbose_name='公告内容')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='公告编号')),
                ('title', models.CharField(max_length=255, verbose_name='公告标题')),
                ('context', models.TextField(verbose_name='公告内容')),
                ('file', models.FileField(blank=True, upload_to='files/', verbose_name='公告附件')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('createName', models.CharField(default='admin', max_length=64, verbose_name='创建人')),
            ],
        ),
    ]
