# Generated by Django 4.0.4 on 2023-02-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_information_createname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='公告编号'),
        ),
    ]
