# Generated by Django 4.0.4 on 2023-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_information_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackUser',
            fields=[
                ('userId', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('cancelTime', models.DateTimeField(verbose_name='失效时间')),
                ('blackCause', models.TextField(default='系统拉黑', verbose_name='公告内容')),
            ],
        ),
    ]
