# Generated by Django 4.0.4 on 2023-02-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_blackuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackuser',
            name='cancelTime',
            field=models.DateTimeField(verbose_name='解除时间'),
        ),
    ]
